### PR TITLE
Initial Layout Idea

### PR DESCRIPTION
**Pull request by jasonfigueroa**
# Just an idea
Open to suggestions and contributions or we can completely rewrite it, it's up to you guys.

### CODE REVIEW

**Comment by lissagoforth** [comment]
Lets add more goats!

**Comment by MidbossK** [comment]
OH YEAAAAHHHHHHHHHHH! -Kool-aid man

**Comment by jasonfigueroa** [comment]
# Maybe Enough to Get Us Started

- added a footer with some social media icons
  - I think we can change the spacing and the layout in the footer later
- Added some goats
- couldn't get the other gif to work properly
  - can add it later

**Comment by jasonfigueroa** [comment]
# Latest Layout
- Increased the font-size of the nav and footer
- Changed the color and background color of the nav, footer and content section
- Centered the navigation links in nav

**Comment by lissagoforth** [comment]
👍

**Pull request merged**
